//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeSyndicateBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoeSyndicateBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap aisling {
            get {
                object obj = ResourceManager.GetObject("aisling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap aisling_f {
            get {
                object obj = ResourceManager.GetObject("aisling_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap aisling_i {
            get {
                object obj = ResourceManager.GetObject("aisling_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap aisling_r {
            get {
                object obj = ResourceManager.GetObject("aisling_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap aisling_t {
            get {
                object obj = ResourceManager.GetObject("aisling_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cameria {
            get {
                object obj = ResourceManager.GetObject("cameria", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cameria_f {
            get {
                object obj = ResourceManager.GetObject("cameria_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cameria_i {
            get {
                object obj = ResourceManager.GetObject("cameria_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cameria_r {
            get {
                object obj = ResourceManager.GetObject("cameria_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap cameria_t {
            get {
                object obj = ResourceManager.GetObject("cameria_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Currency과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/currencyoverview?type=Currency&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrencyRestUrl {
            get {
                return ResourceManager.GetString("CurrencyRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DivinationCard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DivinationCard {
            get {
                return ResourceManager.GetString("DivinationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/itemoverview?type=DivinationCard&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DivinationCardRestUrl {
            get {
                return ResourceManager.GetString("DivinationCardRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap elreon {
            get {
                object obj = ResourceManager.GetObject("elreon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap elreon_f {
            get {
                object obj = ResourceManager.GetObject("elreon_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap elreon_i {
            get {
                object obj = ResourceManager.GetObject("elreon_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap elreon_r {
            get {
                object obj = ResourceManager.GetObject("elreon_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap elreon_t {
            get {
                object obj = ResourceManager.GetObject("elreon_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Essence과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Essence {
            get {
                return ResourceManager.GetString("Essence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/itemoverview?type=Essence&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EssenceRestUrl {
            get {
                return ResourceManager.GetString("EssenceRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fossil과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Fossil {
            get {
                return ResourceManager.GetString("Fossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/itemoverview?type=Fossil&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FossilRestUrl {
            get {
                return ResourceManager.GetString("FossilRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fragment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Fragment {
            get {
                return ResourceManager.GetString("Fragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/currencyoverview?type=Fragment&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FragmentRestUrl {
            get {
                return ResourceManager.GetString("FragmentRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap gravicius {
            get {
                object obj = ResourceManager.GetObject("gravicius", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap gravicius_f {
            get {
                object obj = ResourceManager.GetObject("gravicius_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap gravicius_i {
            get {
                object obj = ResourceManager.GetObject("gravicius_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap gravicius_r {
            get {
                object obj = ResourceManager.GetObject("gravicius_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap gravicius_t {
            get {
                object obj = ResourceManager.GetObject("gravicius_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap guff {
            get {
                object obj = ResourceManager.GetObject("guff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap guff_f {
            get {
                object obj = ResourceManager.GetObject("guff_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap guff_i {
            get {
                object obj = ResourceManager.GetObject("guff_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap guff_r {
            get {
                object obj = ResourceManager.GetObject("guff_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap guff_t {
            get {
                object obj = ResourceManager.GetObject("guff_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap haku {
            get {
                object obj = ResourceManager.GetObject("haku", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap haku_f {
            get {
                object obj = ResourceManager.GetObject("haku_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap haku_i {
            get {
                object obj = ResourceManager.GetObject("haku_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap haku_r {
            get {
                object obj = ResourceManager.GetObject("haku_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap haku_t {
            get {
                object obj = ResourceManager.GetObject("haku_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hillock {
            get {
                object obj = ResourceManager.GetObject("hillock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hillock_f {
            get {
                object obj = ResourceManager.GetObject("hillock_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hillock_i {
            get {
                object obj = ResourceManager.GetObject("hillock_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hillock_r {
            get {
                object obj = ResourceManager.GetObject("hillock_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap hillock_t {
            get {
                object obj = ResourceManager.GetObject("hillock_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Incubator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Incubator {
            get {
                return ResourceManager.GetString("Incubator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/itemoverview?type=Incubator&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IncubatorRestUrl {
            get {
                return ResourceManager.GetString("IncubatorRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap it_that_fled {
            get {
                object obj = ResourceManager.GetObject("it_that_fled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap it_that_fled_f {
            get {
                object obj = ResourceManager.GetObject("it_that_fled_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap it_that_fled_i {
            get {
                object obj = ResourceManager.GetObject("it_that_fled_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap it_that_fled_r {
            get {
                object obj = ResourceManager.GetObject("it_that_fled_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap it_that_fled_t {
            get {
                object obj = ResourceManager.GetObject("it_that_fled_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap janus {
            get {
                object obj = ResourceManager.GetObject("janus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap janus_f {
            get {
                object obj = ResourceManager.GetObject("janus_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap janus_i {
            get {
                object obj = ResourceManager.GetObject("janus_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap janus_r {
            get {
                object obj = ResourceManager.GetObject("janus_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap janus_t {
            get {
                object obj = ResourceManager.GetObject("janus_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jorgin {
            get {
                object obj = ResourceManager.GetObject("jorgin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jorgin_f {
            get {
                object obj = ResourceManager.GetObject("jorgin_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jorgin_i {
            get {
                object obj = ResourceManager.GetObject("jorgin_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jorgin_r {
            get {
                object obj = ResourceManager.GetObject("jorgin_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap jorgin_t {
            get {
                object obj = ResourceManager.GetObject("jorgin_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap korell {
            get {
                object obj = ResourceManager.GetObject("korell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap korell_f {
            get {
                object obj = ResourceManager.GetObject("korell_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap korell_i {
            get {
                object obj = ResourceManager.GetObject("korell_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap korell_r {
            get {
                object obj = ResourceManager.GetObject("korell_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap korell_t {
            get {
                object obj = ResourceManager.GetObject("korell_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap leo {
            get {
                object obj = ResourceManager.GetObject("leo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap leo_f {
            get {
                object obj = ResourceManager.GetObject("leo_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap leo_i {
            get {
                object obj = ResourceManager.GetObject("leo_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap leo_r {
            get {
                object obj = ResourceManager.GetObject("leo_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap leo_t {
            get {
                object obj = ResourceManager.GetObject("leo_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Map과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/itemoverview?type=Map&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MapRestUrl {
            get {
                return ResourceManager.GetString("MapRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberImagePath {
            get {
                return ResourceManager.GetString("MemberImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Json/member.json과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemberJsonPath {
            get {
                return ResourceManager.GetString("MemberJsonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /Resources/과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RewardImagePath {
            get {
                return ResourceManager.GetString("RewardImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap riker {
            get {
                object obj = ResourceManager.GetObject("riker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap riker_f {
            get {
                object obj = ResourceManager.GetObject("riker_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap riker_i {
            get {
                object obj = ResourceManager.GetObject("riker_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap riker_r {
            get {
                object obj = ResourceManager.GetObject("riker_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap riker_t {
            get {
                object obj = ResourceManager.GetObject("riker_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rin {
            get {
                object obj = ResourceManager.GetObject("rin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rin_f {
            get {
                object obj = ResourceManager.GetObject("rin_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rin_i {
            get {
                object obj = ResourceManager.GetObject("rin_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rin_r {
            get {
                object obj = ResourceManager.GetObject("rin_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap rin_t {
            get {
                object obj = ResourceManager.GetObject("rin_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Scarab과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Scarab {
            get {
                return ResourceManager.GetString("Scarab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/itemoverview?type=Scarab&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ScarabRestUrl {
            get {
                return ResourceManager.GetString("ScarabRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/itemoverview?type=SkillGem&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SkillGemRestUrl {
            get {
                return ResourceManager.GetString("SkillGemRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap tora {
            get {
                object obj = ResourceManager.GetObject("tora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap tora_f {
            get {
                object obj = ResourceManager.GetObject("tora_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap tora_i {
            get {
                object obj = ResourceManager.GetObject("tora_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap tora_r {
            get {
                object obj = ResourceManager.GetObject("tora_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap tora_t {
            get {
                object obj = ResourceManager.GetObject("tora_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   UniqueMap과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UniqueMap {
            get {
                return ResourceManager.GetString("UniqueMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://poe.ninja/api/data/itemoverview?type=UniqueMap&amp;league=과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UniqueMapRestUrl {
            get {
                return ResourceManager.GetString("UniqueMapRestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vagan {
            get {
                object obj = ResourceManager.GetObject("vagan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vagan_f {
            get {
                object obj = ResourceManager.GetObject("vagan_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vagan_i {
            get {
                object obj = ResourceManager.GetObject("vagan_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vagan_r {
            get {
                object obj = ResourceManager.GetObject("vagan_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vagan_t {
            get {
                object obj = ResourceManager.GetObject("vagan_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vorici {
            get {
                object obj = ResourceManager.GetObject("vorici", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vorici_f {
            get {
                object obj = ResourceManager.GetObject("vorici_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vorici_i {
            get {
                object obj = ResourceManager.GetObject("vorici_i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vorici_r {
            get {
                object obj = ResourceManager.GetObject("vorici_r", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap vorici_t {
            get {
                object obj = ResourceManager.GetObject("vorici_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
